name: Chocolate
favicon: null
layout_spectrum: 0.24764206702820957
typography_spectrum: 0.2967448004055768
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3c2921'
    - '#dfc3a0'
    - '#951b81'
    - '#6d5747'
    - '#da6176'
  brandStrength: 0
  lightness: 0
  saturation: 1
  rhythmicContrast: 0.5
purpose: []
