name: Chocolate
favicon: null
layout_spectrum: 0.24764206702820957
typography_spectrum: 0.2967448004055768
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.3565160834696144
  lightness: 0.5232268664985895
  saturation: 0.9693059055134654
  rhythmicContrast: 0.15228579728864133
purpose: []
